apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: JSVAR_DOCKERIMAGE
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  type: NodePort
  selector:
    app: homepage
  ports:
  - protocol: TCP
    port: 80  
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homepage-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /homepage/(.*)
          backend:
            serviceName: homepage-service
            servicePort: 80
